simulator:
  fps      : 500  # 100 fps
  sim_step : 100  # Maximun LCP solver step
  dist_threshold: 5e-2 # Distance to decide whether to calculate parameters
  frame_skip: 40
  visualize : human # None, human

display:
  WIDTH : 1024
  HEIGHT: 1024
  unit:   0.001953125 # [m/pixel]

pusher:
  pusher_num      : 3

  pusher_angle    : 120
  pusher_distance : 0.04
  # pusher_d_u_limit: 0.185
  pusher_d_u_limit: 0.19
  pusher_d_l_limit: 0.06
  pusher_type     : {"type": "superellipse", "a": 0.015, "b": 0.03, "n": 10}

  pusher_position : [0.0, -1.2]
  pusher_rotation : 0

  unit_v_speed    : 0.25  # [m/s]
  unit_r_speed    : 2.00  # [rad/s]
  unit_w_speed    : 0.25   # [m/s]

sliders:
  [
    ## Polygons
    {"type": "srpolygon",  'q':[-0.5, -0.25, 0.0] ,  "a": 0.15, "k": 6},
  ]

obstacles:
  [
  ]

auto:
  maximun_number : 15
  minimum_radius : 0.05
  maximum_radius : 0.125
